theme: bento
languageCode: en-us
baseurl: https://www.example.com/
title: dssquad
author: The dssquad Team
copyright: dssquad
taxonomies:
  category: categories
  disqusShortname: bento-hugo-theme
  googleAnalytics: UA-XXXXXX-YY
  pygmentsCodefences: yes
  pygmentsStyle: vs
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: github
params:
  authorBio: dssquad is a group of data professionals building the future with data
  avatar: images/avatar.png
  copyright: Copyright © 2020 dssquad
  cover: images/vancouver.jpg
  description: This is a platform to document the project taken by dssquad to develop a solution of predicting crime rates in Buffalo city based on other known factors.
  email: email@xxxx.com
  fathomAnalytics:
    serverURL: analytics.example.com
    siteID: XXXXX
  github: XXXX
  headline: Data Project Documentation
  intro: yes
  linkedin: https://linkedin.com/in/XXXX
  ogImage: images/og_image.jpg
  twitter: XXXX
  umami:
    siteID: XXXXX
    trackerScript: //umami.example.com/umami.js
menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Meet The Team
      url: /archives
      weight: 2
    - name: Blogs
      url: https://github.com/leonardofaria/bento
      weight: 3
    - name: Archives
      url: /about
      weight: 4
